kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
      ruleSelectorNilUsesHelmValues: false
      ruleNamespaceSelector: {}
      ruleSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      retention: 2h
      livenessProbeInitialDelaySeconds: 60
      readinessProbeInitialDelaySeconds: 30
      resources:
        requests: { cpu: 100m, memory: 256Mi }
        limits:   { memory: 768Mi }
  grafana:
    podLabels:
      demo.gitops: live
    adminPassword: prom-operator
    defaultDashboardsEnabled: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: argocd
            orgId: 1
            folder: Argo CD
            type: file
            disableDeletion: true
            editable: false
            options: { path: /var/lib/grafana/dashboards/argocd }
    dashboardsConfigMaps:
      argocd: argocd-grafana-dashboard
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        label: grafana_dashboard
        labelValue: "1"
    resources:
      requests: { cpu: 50m, memory: 96Mi }
      limits:   { cpu: 300m, memory: 256Mi }
  alertmanager:
    enabled: false
  prometheusOperator:
    resources:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 300m, memory: 256Mi }
    livenessProbe:  { initialDelaySeconds: 30, periodSeconds: 20, timeoutSeconds: 10, failureThreshold: 6 }
    readinessProbe: { initialDelaySeconds: 15, periodSeconds: 20, timeoutSeconds: 10, failureThreshold: 6 }
  kube-state-metrics:
    resources:
      requests: { cpu: 30m, memory: 48Mi }
      limits:   { cpu: 200m, memory: 192Mi }
    livenessProbe:  { initialDelaySeconds: 30, periodSeconds: 20, timeoutSeconds: 10, failureThreshold: 6 }
    readinessProbe: { periodSeconds: 20, timeoutSeconds: 10, failureThreshold: 6 }
  prometheus-node-exporter:
    resources:
      requests: { cpu: 20m, memory: 32Mi }
      limits:   { cpu: 200m, memory: 96Mi }
  coreDns: { enabled: false }
  kubeDns: { enabled: false }
  kubelet: { enabled: false }
  kubeEtcd: { enabled: false }
  kubeScheduler: { enabled: false }
  kubeControllerManager: { enabled: false }
  kubeProxy: { enabled: false }
